
name: Continuous Delivery
on:
    push:
        branches:
            - main #ou qualquer outra branch
jobs:
    deliver:
        run-on: ubuntu-latest
        steps:
            - name: Check out repository code
            uses: actions/checkout@v4

            - name: Simulando Continuos Delivery
            - uses: actions/upload-artifact@v4
            with:
                name: projetozipado.zip
                path:
                    '**.py'
                    README.MD
